[versions]
agp = "8.2.2"

compileSdk = "34"
minSdk = "23"
targetSdk = "34"

# F-Droid depends on the format of the two lines below to update
versionCode = "7050000"
versionName = "7.5.0"

kotlin = "1.9.23"

dagger = "2.51"

detekt = "1.23.5"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }

versions = "com.github.ben-manes.versions:0.51.0"
dependencyGuard = "com.dropbox.dependency-guard:0.5.0"

gms = "com.google.gms.google-services:4.4.1"
secrets = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:2.0.1"

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.0.4"
tools = "com.github.DeweyReed:tools:0.7.0"

kotlin-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0"
kotlin-coroutines-play = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.8.0"
kotlin-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.0"

junit = "junit:junit:4.13.2"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:5.2.1"
mockito-core = "org.mockito:mockito-core:5.11.0"
mockito-android = "org.mockito:mockito-android:5.11.0"
androidx-test-arch = "androidx.arch.core:core-testing:2.2.0"

androidx-test-core = "androidx.test:core:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-junit = "androidx.test.ext:junit:1.1.5"
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
androidx-test-espresso-contrib = "androidx.test.espresso:espresso-contrib:3.5.1"
androidx-test-espresso-intents = "androidx.test.espresso:espresso-intents:3.5.1"

androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-fragment = "androidx.fragment:fragment:1.6.2"
androidx-recyclerView = "androidx.recyclerview:recyclerview:1.3.0"
androidx-preference = "androidx.preference:preference:1.2.1"
androidx-constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.7.0"
androidx-lifecycle-liveData = "androidx.lifecycle:lifecycle-livedata-ktx:2.7.0"
androidx-lifecycle-viewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0"
androidx-customTabs = "androidx.browser:browser:1.8.0"
androidx-dynamicAnimation = "androidx.dynamicanimation:dynamicanimation:1.0.0"
androidx-media = "androidx.media:media:1.7.0"
androidx-core = "androidx.core:core-ktx:1.12.0"
androidx-collection = "androidx.collection:collection-ktx:1.4.0"

androidx-room-runtime = "androidx.room:room-runtime:2.6.1"
androidx-room-compiler = "androidx.room:room-compiler:2.6.1"
androidx-room-ktx = "androidx.room:room-ktx:2.6.1"
androidx-room-test = "androidx.room:room-testing:2.6.1"

androidx-navigation-fragment = "androidx.navigation:navigation-fragment-ktx:2.7.7"
androidx-navigation-ui = "androidx.navigation:navigation-ui-ktx:2.7.7"

androidx-work = "androidx.work:work-runtime-ktx:2.9.0"

material = "com.google.android.material:material:1.4.0"

leakCannary = "com.squareup.leakcanary:leakcanary-android-startup:2.13"
timber = "com.jakewharton.timber:timber:5.0.1"

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
hilt-navigation = "androidx.hilt:hilt-navigation-fragment:1.2.0"
hilt-work = "androidx.hilt:hilt-work:1.2.0"
hilt-work-compiler = "androidx.hilt:hilt-compiler:1.2.0"

moshi = "com.squareup.moshi:moshi:1.15.1"
moshi-kotlinGen = "com.squareup.moshi:moshi-kotlin-codegen:1.15.1"

billing = "com.android.billingclient:billing-ktx:6.2.0"
firebase_bom = "com.google.firebase:firebase-bom:32.8.0"
firebase_auth = { module = "com.google.firebase:firebase-auth" }
firebase_auth_ui = "com.firebaseui:firebase-ui-auth:8.0.2"
firebase_storage = { module = "com.google.firebase:firebase-storage" }
playServices_auth = "com.google.android.gms:play-services-auth:21.0.0"
playServices_review = "com.google.android.play:review-ktx:2.0.1"

appcenter_crashes = "com.microsoft.appcenter:appcenter-crashes:5.0.4"

androidJob = "com.github.DeweyReed:android-job:a04c817792"
okio = "com.squareup.okio:okio:3.9.0"
permission = "pub.devrel:easypermissions:3.0.0"

fastAdapter = "com.mikepenz:fastadapter:5.7.0"
fastAdapter_binding = "com.mikepenz:fastadapter-extensions-binding:5.7.0"
fastAdapter_expandable = "com.mikepenz:fastadapter-extensions-expandable:5.7.0"

materialDialog-core = "com.afollestad.material-dialogs:core:0.9.6.0"
materialDialog-common = "com.afollestad.material-dialogs:commons:0.9.6.0"

calendarView = "com.github.kizitonwose:CalendarView:1.0.4"
chart = "com.github.PhilJay:MPAndroidChart:v3.1.0"
chromeMenu = "xyz.aprildown:ChromeMenu:0.1.1"
flexbox = "com.google.android.flexbox:flexbox:3.0.0"
hmsPicker = "xyz.aprildown:HmsPickerView:0.2.0"
konfetti = "nl.dionsegijn:konfetti:1.3.2"
materialDrawer = "com.mikepenz:materialdrawer:8.4.5"
materialPopupMenu = "com.github.zawadz88.materialpopupmenu:material-popup-menu:4.1.0"
materialize = "com.mikepenz:materialize:1.2.1"
scrollHmsPicker = "xyz.aprildown:ScrollHmsPicker:2.0.3"
theme = "xyz.aprildown:Theme:0.4.0"
toggleButtonGroup = "com.nex3z:toggle-button-group:1.2.3"
ultimateRingtonePicker = "com.github.DeweyReed:UltimateRingtonePicker:3.3.0-RC1"
verticalStepperForm = "com.ernestoyaquello.stepperform:vertical-stepper-form:2.5.0"
zip4j = "net.lingala.zip4j:zip4j:2.11.5"
taskerPlugin = "com.joaomgcd:taskerpluginlibrary:0.4.10"
diskLruCache = "com.github.bumptech.glide:disklrucache:4.16.0"

[bundles]
mockito-core = ["mockito-kotlin", "mockito-core"]
mockito-android = ["mockito-kotlin", "mockito-android"]
androidx-test = [
    "androidx-test-core",
    "androidx-test-runner",
    "androidx-test-rules",
    "androidx-test-junit",
]
androidx-test-espresso = [
    "androidx-test-espresso-core",
    "androidx-test-espresso-contrib",
    "androidx-test-espresso-intents",
]
